name: Backend CI/CD
on:
  push:
    paths:
      - "hookdb-api/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: 44.223.155.116
          username: ubuntu
          key: "${{ secrets.AWS_SERVER }}"
          script: echo "Conexión exitosa"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Build App
        run: mvn clean package -DskipTests
      - name: Get short SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_BACK }}
          password: ${{ secrets.DOCKERHUB_TOKEN_BACK }}
      - name: Build and Push Docker Images
        run: |
          docker buildx create --name multi-arch-builder --use
          docker buildx build --builder multi-arch-builder --platform linux/amd64,linux/arm64 -t davdportillo/winning-station:${{ steps.sha.outputs.sha }} --build-arg GIT_COMMIT=${{ steps.sha.outputs.sha }} --push .
          docker buildx imagetools create --tag davdportillo/winning-station:latest davdportillo/winning-station:${{ steps.sha.outputs.sha }}
          docker buildx imagetools push davdportillo/winning-station:latest
          docker buildx imagetools push davdportillo/winning-station:${{ steps.sha.outputs.sha }}
          docker buildx rm multi-arch-builder
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 44.223.155.116
          username: ubuntu
          key: ${{ secrets.AWS_SERVER }}
          script: |
            cd k8s
            helm upgrade --install winning-station ./winning-station --set app.image=davdportillo/winning-station:${{ steps.sha.outputs.sha }}
      - name: Cleanup Docker Images on Server
        uses: appleboy/ssh-action@master
        with:
          host: 44.223.155.116
          username: ubuntu
          key: ${{ secrets.AWS_SERVER }}
          script: docker image prune -a -f
